---
:concurrency: 40
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :concurrency: 20
  :timeout: 30
:queues:
  - [sunspot, 7]
  - [default, 5]
  - [mass_upload, 1]
  - [paperclip,2]
  - [fastbill, 5]
