---
:concurrency: 40
staging:
  :concurrency: 10
production:
  :concurrency: 30
  :timeout: 550
:queues:
  - [sidekiq_pro, 1]
  - [default, 5]
  - [mass_upload, 3]
  - [mass_upload_rows, 3]
  - [mass_uploads_finish, 1]
  - [paperclip_background, 1]
  - [paperclip_foreground, 4]
  - [fastbill, 5]
  - [indexing, 4]
  - [statistics, 2]
  - [after_buy, 5]
  - [cart_mails, 5]
  - [cleanup, 2]
  - [file_normalizer, 2]
  - [heavy_mass_upload, 3]
  - [heavy_mass_upload_rows, 3]
  - [cancellation_normalizer, 3]
  - [broken_file_finder, 2]
  - [belboon_csv_export, 2]
