width : "100%"
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1: "bold,italic,underline,strikethrough,undo,redo,|,cut,copy,paste,bullist,numlist,outdent,indent"
theme_advanced_buttons2: "formatselect,fontselect,fontsizeselect"
theme_advanced_buttons3: "justifyleft,justifycenter,justifyright,justifyfull,|,link,unlink,anchor,image,code,tablecontrols|,forecolor,backcolor"
plugins :
  - table